name: Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install        
    - name: Test Linting
      run: npm run lint
    - name: Unit Testing
      run: npm test
      env:
        JWT_SECRET: ${{secrets.JWT_SECRET}}
    - name: Deploy Production to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "api-immersis"
        heroku_email: "officialimmersis@gmail.com"
